"""
ComfyUI-EddySevenResonance
7-Resonance Seed Generator Nodes
Author: eddy
"""

from .eddy_int_seven import NODE_CLASS_MAPPINGS as INT_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as INT_NAMES
from .eddy_lucky_seed_node import NODE_CLASS_MAPPINGS as LUCKY_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LUCKY_NAMES
from .seed_receiver_test import NODE_CLASS_MAPPINGS as TEST_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEST_NAMES

# Merge all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(INT_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LUCKY_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TEST_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(INT_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(LUCKY_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(TEST_NAMES)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
